DATA_BASE = "users_books.db"

# Author table
AUTHOR_TABLE_NAME = "authors"
AUTHOR_NAME_COLUMN = "author_name"
AUTHOR_ID_COLUMN_NAME = "author_id"

# Authors_books table
AUTHOR_BOOKS_TABLE_NAME = "authors_books"
AUTHOR_BOOKS_AUTHOR_ID = "author_id"
AUTHOR_BOOKS_BOOK_ID = "book_id"

# Book table
BOOK_TABLE_NAME = "books"
BOOK_NAME_COLUMN = "book_name"
BOOK_ISBN_COLUMN = "isbn"
BOOK_ID_COLUMN_NAME = "book_id"
BOOK_PUBLICATION_YEAR_COLUMN_NAME = "publication_year"
BOOK_FORMAT_COLUMN_NAME = "format"
BOOK_DATE_READ_COLUMN_NAME = "date_read"
BOOK_CATEGORIES_COLUMN_NAME = "categories"
BOOK_REVIEW_COLUMN_NAME = "review"

ALOWED_TABLES = {BOOK_TABLE_NAME, AUTHOR_BOOKS_TABLE_NAME, AUTHOR_TABLE_NAME}

ALLOWED_TABLE_COLUMNS = {AUTHOR_NAME_COLUMN, AUTHOR_ID_COLUMN_NAME, AUTHOR_BOOKS_TABLE_NAME, AUTHOR_BOOKS_BOOK_ID, BOOK_NAME_COLUMN, BOOK_ISBN_COLUMN, BOOK_ID_COLUMN_NAME, BOOK_PUBLICATION_YEAR_COLUMN_NAME, BOOK_FORMAT_COLUMN_NAME, BOOK_DATE_READ_COLUMN_NAME, BOOK_CATEGORIES_COLUMN_NAME, BOOK_REVIEW_COLUMN_NAME
}